version: 3.0.0.{build}
image: Visual Studio 2015
branches:
  only:
    - master
    - develop
build_script:
  - build.cmd --target=build --configuration=Release
  - build.cmd --target=tests --configuration=Release
  - build.cmd --target=pack --configuration=Release 
test: off
deploy: off 
artifacts:
  - path: TestResult.xml
  - path: 'packages\*.nupkg'